# Generated by Django 5.0.6 on 2024-07-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', null=0, upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
