# Generated by Django 5.0.6 on 2024-08-04 20:26

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=1, null=1),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(null=0, upload_to=job.models.image_dir),
        ),
    ]
