# Generated by Django 5.0.6 on 2024-08-05 01:41

import django.db.models.deletion
import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_slug_alter_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_applies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('web_link', models.URLField()),
                ('cv', models.FileField(null=0, upload_to=job.models.cv_dir)),
                ('covletter', models.TextField(max_length=1000)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job')),
            ],
        ),
    ]
