# Generated by Django 5.0.6 on 2024-08-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_applies'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applies',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
