# Generated by Django 5.0.6 on 2024-08-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
